title: 2022 Texas Darts Masters
description: Darts Atlas will be sponsoring *at least* one player from Texas with an all-expenses-paid trip to compete in the North American Darts Championship Qualifiers.
url: https://TexasDartsMasters.com
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
plugins:
  - jekyll-include-cache
  - jemoji
